# Generated by Django 3.2.5 on 2021-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.CharField(max_length=10000),
        ),
    ]
